// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_sync_flutter_libs/objectbox_sync_flutter_libs.dart';

import 'models/entry.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 3185421778488833173),
      name: 'Entry',
      lastPropertyId: const IdUid(6, 2348572108863653669),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6748782309025418619),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 431641478109028022),
            name: 'date',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 181055550323512722),
            name: 'mass',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 5352249710119682315),
            name: 'fluid',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 8498620085953854879),
            name: 'bPS',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 2348572108863653669),
            name: 'bPD',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 3185421778488833173),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Entry: EntityDefinition<Entry>(
        model: _entities[0],
        toOneRelations: (Entry object) => [],
        toManyRelations: (Entry object) => {},
        getId: (Entry object) => object.id,
        setId: (Entry object, int id) {
          object.id = id;
        },
        objectToFB: (Entry object, fb.Builder fbb) {
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.date.millisecondsSinceEpoch);
          fbb.addFloat64(2, object.mass);
          fbb.addFloat64(3, object.fluid);
          fbb.addInt64(4, object.bPS);
          fbb.addInt64(5, object.bPD);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Entry(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              date: DateTime.fromMillisecondsSinceEpoch(
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0)),
              mass:
                  const fb.Float64Reader().vTableGet(buffer, rootOffset, 8, 0),
              fluid:
                  const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0),
              bPS: const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
              bPD: const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Entry] entity fields to define ObjectBox queries.
class Entry_ {
  /// see [Entry.id]
  static final id = QueryIntegerProperty<Entry>(_entities[0].properties[0]);

  /// see [Entry.date]
  static final date = QueryIntegerProperty<Entry>(_entities[0].properties[1]);

  /// see [Entry.mass]
  static final mass = QueryDoubleProperty<Entry>(_entities[0].properties[2]);

  /// see [Entry.fluid]
  static final fluid = QueryDoubleProperty<Entry>(_entities[0].properties[3]);

  /// see [Entry.bPS]
  static final bPS = QueryIntegerProperty<Entry>(_entities[0].properties[4]);

  /// see [Entry.bPD]
  static final bPD = QueryIntegerProperty<Entry>(_entities[0].properties[5]);
}
